schema_version = "1.0.0"
id = "classic_hide_collections_keymap"
name = "Classic Hide Collections Keymap"
version = "1.0.0"
tagline = "Classic Hide Collections Keymap"
maintainer = "Community"
type = "add-on"
tags = ["3D View", "System", "User Interface"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]

